name: Automated Tests
on: pull_request
jobs:
  buzzy-finance-integration-tests:
    name: Build, Test, and Lint with Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable bun
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: "bun"
          cache-dependency-path: package-lock.json

      - run: bun install --frozen-lockfile
      - run: bun build
      - run: bun test
      - run: bun lint:check
