name: Automated Tests
on: pull_request
jobs:
  buzzy-finance-integration-tests:
    name: Build, Test, and Lint with Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun build
      - run: bun test
      - run: bun lint:check
